# -*- coding: utf-8 -*-
"""評分.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osGSxhUrEdT_CcaYy-FCSdE1N7zJ_6In
"""



import os
import json
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import base64
import requests

# 使用 Google Cloud Vision API 進行字符辨識並提取骨架信息
def recognize_character_with_vision_api(image_path, api_key):
    try:
        with open(image_path, 'rb') as image_file:
            content = image_file.read()
        encoded_image = base64.b64encode(content).decode('utf-8')

        vision_url = f'https://vision.googleapis.com/v1/images:annotate?key={api_key}'
        headers = {'Content-Type': 'application/json'}
        body = {
            'requests': [{
                'image': {
                    'content': encoded_image
                },
                'features': [{
                    'type': 'TEXT_DETECTION'
                }],
                'imageContext': {
                    'languageHints': ['zh']
                }
            }]
        }

        response = requests.post(vision_url, headers=headers, data=json.dumps(body))
        if response.status_code != 200:
            print(f"API 請求失敗，狀態碼：{response.status_code}")
            print("回應內容：", response.text)  # 輸出完整的回應內容
            return None, None

        response_data = response.json()
        if 'responses' in response_data and 'textAnnotations' in response_data['responses'][0]:
            ocr_result = response_data['responses'][0]['textAnnotations'][0]['description']
            ch_unicode = format(ord(ocr_result.strip()[0]), '04x')
            print(f"識別的字符: {ocr_result}")
            print(f"Unicode: {ch_unicode}")
            return ocr_result, ch_unicode
        else:
            print("未檢測到文本", response_data)
            return None, None
    except Exception as e:
        print(f"在 recognize_character_with_vision_api 中出錯: {e}")
        return None, None

# 圖像預處理
def preprocess_image_for_ocr(image_path):
    # 讀取圖像
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    # 高斯模糊來降低噪點
    image = cv2.GaussianBlur(image, (5, 5), 0)

    # 自適應閾值處理以強化文字對比度
    image = cv2.adaptiveThreshold(image, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)

    # 使用形態學運算來去除噪點 (開運算: 先腐蝕後膨脹)
    kernel = np.ones((3, 3), np.uint8)
    image = cv2.morphologyEx(image, cv2.MORPH_OPEN, kernel)

    # 調整圖像大小 (可選)
    image = cv2.resize(image, None, fx=1.5, fy=1.5, interpolation=cv2.INTER_LINEAR)

    # 將處理後的圖像保存回原圖像路徑
    cv2.imwrite(image_path, image)

    return image_path


# 判斷兩個線段是否相似
def are_segments_similar(seg1, seg2, distance_threshold=10, angle_threshold=5):
    center1 = ((seg1['Sx'] + seg1['Ex']) / 2, (seg1['Sy'] + seg1['Ey']) / 2)
    center2 = ((seg2['Sx'] + seg2['Ex']) / 2, (seg2['Sy'] + seg2['Ey']) / 2)
    distance = np.linalg.norm(np.array(center1) - np.array(center2))
    angle1 = np.arctan2(seg1['Ey'] - seg1['Sy'], seg1['Ex'] - seg1['Sx'])
    angle2 = np.arctan2(seg2['Ey'] - seg2['Sy'], seg2['Ex'] - seg2['Sx'])
    angle_difference = np.degrees(np.abs(angle1 - angle2))
    if distance < distance_threshold and angle_difference < angle_threshold:
        return True
    return False

# 合併相似線段
def merge_similar_segments(df):
    merged_lines = []
    used_segments = set()

    for i, seg1 in df.iterrows():
        if i in used_segments:
            continue
        for j, seg2 in df.iterrows():
            if i != j and j not in used_segments:
                if are_segments_similar(seg1, seg2):
                    merged_segment = {
                        'Sx': (seg1['Sx'] + seg2['Sx']) / 2,
                        'Sy': (seg1['Sy'] + seg2['Sy']) / 2,
                        'Ex': (seg1['Ex'] + seg2['Ex']) / 2,
                        'Ey': (seg1['Ey'] + seg2['Ey']) / 2
                    }
                    merged_lines.append(merged_segment)
                    used_segments.add(i)
                    used_segments.add(j)
                    break
        else:
            merged_lines.append(seg1)

    return pd.DataFrame(merged_lines)

# 從圖片提取線段，返回處理後的 DataFrame
def extract_line_segments(image_path):
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    edges = cv2.Canny(image, 50, 150)
    contours, _ = cv2.findContours(edges, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    lines = []

    for contour in contours:
        for i in range(len(contour) - 1):
            Sx, Sy = contour[i][0]
            Ex, Ey = contour[i + 1][0]
            lines.append([Sx, Sy, Ex, Ey])

    df = pd.DataFrame(lines, columns=['Sx', 'Sy', 'Ex', 'Ey'])

    # 合併相似的線段
    df = merge_similar_segments(df)

    return df

# 定義中心對齊和縮放函數
def center_and_scale(coords):
    center_x = (coords[:, 0] + coords[:, 2]) / 2
    center_y = (coords[:, 1] + coords[:, 3]) / 2
    center = np.array([np.mean(center_x), np.mean(center_y)])

    coords_centered = coords - np.tile(center, 2)

    min_x = np.min(coords_centered[:, [0, 2]])
    max_x = np.max(coords_centered[:, [0, 2]])
    min_y = np.min(coords_centered[:, [1, 3]])
    max_y = np.max(coords_centered[:, [1, 3]])

    scale_x = max_x - min_x
    scale_y = max_y - min_y
    scale = max(scale_x, scale_y)

    coords_scaled = coords_centered / scale

    return coords_scaled

# 檢查兩組線段的長度，如果一組較短，則使用插值來增加其線段數量，使其與較長的一組對齊。
def align_segments(coords1, coords2):
    len1, len2 = len(coords1), len(coords2)

    if len1 > len2:
        coords2 = interpolate_segments(coords2, len1)
    elif len2 > len1:
        coords1 = interpolate_segments(coords1, len2)

    return coords1, coords2

# 對線段數較少的檔案進行差值，以匹配線段數量
def interpolate_segments(coords, target_length):
    if len(coords) >= target_length:
        return coords

    interpolated_coords = []
    for i in range(len(coords) - 1):
        interpolated_coords.append(coords[i])
        # 線性插值
        while len(interpolated_coords) < target_length and len(interpolated_coords) < len(coords) * target_length:
            new_segment = (coords[i] + coords[i + 1]) / 2
            interpolated_coords.append(new_segment)

    if len(interpolated_coords) < target_length:
        interpolated_coords.append(coords[-1])

    return np.array(interpolated_coords[:target_length])

# 計算相似度的函數（使用指數縮放的平均歐幾里得距離分數）
def calculate_similarity(coords1, coords2, alpha=0.5):
    # 在計算相似度之前，對線段數量進行對齊
    coords1, coords2 = align_segments(coords1, coords2)

    mean_euclidean_distance = np.mean(np.sqrt(np.sum((coords1 - coords2) ** 2, axis=1)))
    euclidean_score = 100 * np.exp(-alpha * mean_euclidean_distance)

    return euclidean_score

# 繪製最相似的字形與目標字形的比對結果
def plot_comparison(target_coords_aligned, best_match):
    plt.figure(figsize=(12, 6))

    # 設置標籤時確保僅顯示一次圖例
    for idx, line in enumerate(target_coords_aligned):
        label = '目標字形' if idx == 0 else ""  # 只為第一個線段設置標籤
        plt.plot([line[0], line[2]], [line[1], line[3]], 'r-', label=label)

    for idx, line in enumerate(best_match):
        label = '最佳匹配' if idx == 0 else ""  # 只為第一個線段設置標籤
        plt.plot([line[0], line[2]], [line[1], line[3]], 'b-', label=label)
    plt.title("Comparison")
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.legend()
    plt.show()



def evaluation(image_path, api_key):
    
    # 預處理圖像
    preprocessed_image_path = preprocess_image_for_ocr(image_path)

    # 使用 Cloud Vision API 進行字符辨識
    recognized_char, recognized_unicode = recognize_character_with_vision_api(preprocessed_image_path, api_key)
    print(recognized_char, recognized_unicode)

    if recognized_unicode:
        # 找出對應的標準字形 CSV 檔案
        base_path = r"C:\xampp\htdocs\Final_project\project"
        csv_folder_path = 'csv_files/csv_files'
        csv_folder_path = os.path.abspath(os.path.join(base_path, csv_folder_path))
        
        #csv_folder_path = '.csv_files/'
        standard_csv_path = os.path.join(csv_folder_path, f'{recognized_unicode}.csv')
        
        if os.path.exists(standard_csv_path):
            print(f"找到標準字形 CSV 檔案: {standard_csv_path}")

            # 提取圖像中的線段
            df = extract_line_segments(image_path)

            # 讀取標準字形和提取到的字形進行比對
            target_coords = df[['Sx', 'Sy', 'Ex', 'Ey']].values
            target_coords_aligned = center_and_scale(target_coords)

            standard_coords = pd.read_csv(standard_csv_path)[['Sx', 'Sy', 'Ex', 'Ey']].values
            standard_coords_aligned = center_and_scale(standard_coords)

            # 計算相似度得分
            similarity_score = calculate_similarity(target_coords_aligned, standard_coords_aligned)
            print(f"相似度得分: {similarity_score:.2f}")

            # 可選：繪製比對結果
            #plot_comparison(target_coords_aligned, standard_coords_aligned)

            return {
                'recognized_char': recognized_char,
                'unicode': recognized_unicode,
                'similarity_score': similarity_score
            }
        else:
            print(f"未找到對應的標準字形 CSV 檔案，Unicode: {recognized_unicode}")
            return {
                'recognized_char': recognized_char,
                'unicode': recognized_unicode,
                'error': '標準字形 CSV 檔案未找到'
            }
    else:
        print("未識別到字符。")
        return {
            'error': '未識別到字符'
        }