-- MySQL Script generated by MySQL Workbench
-- Tue May 14 18:03:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `admin_id` INT NOT NULL,
  `account` VARCHAR(45) NOT NULL,
  `admin_salt` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `permission` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC) VISIBLE,
  UNIQUE INDEX `account_UNIQUE` (`account` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_credential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin_credential` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin_credential` (
  `hash_id` INT NOT NULL,
  `hash_admin_id` INT NOT NULL,
  `hash_admin_pwd` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`hash_id`),
  UNIQUE INDEX `hash_id_UNIQUE` (`hash_id` ASC) VISIBLE,
  UNIQUE INDEX `hash_admin_id_UNIQUE` (`hash_admin_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`character` ;

CREATE TABLE IF NOT EXISTS `mydb`.`character` (
  `character_id` INT NOT NULL,
  `character` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`character_id`),
  UNIQUE INDEX `character_id_UNIQUE` (`character_id` ASC) VISIBLE,
  UNIQUE INDEX `character_UNIQUE` (`character` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`character_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`character_record` ;

CREATE TABLE IF NOT EXISTS `mydb`.`character_record` (
  `record_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `character_id` INT NOT NULL,
  `practice_score` INT NOT NULL,
  `study_time` DATETIME NOT NULL,
  PRIMARY KEY (`record_id`, `user_id`, `character_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `user_character_record_idx` (`user_id` ASC) VISIBLE,
  INDEX `char_char_record_fk_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `user_character_record_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `char_char_record_fk`
    FOREIGN KEY (`character_id`)
    REFERENCES `mydb`.`character` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `course_description` TEXT NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_change`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course_change` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course_change` (
  `changelog_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `change_description` TEXT NULL,
  `course_changecol` VARCHAR(45) NULL,
  `change_by` INT NOT NULL,
  PRIMARY KEY (`changelog_id`, `course_id`, `change_by`),
  INDEX `course_course_change_fk_idx` (`course_id` ASC) VISIBLE,
  INDEX `admin_course_change_fk_idx` (`change_by` ASC) VISIBLE,
  CONSTRAINT `course_course_change_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `admin_course_change_fk`
    FOREIGN KEY (`change_by`)
    REFERENCES `mydb`.`admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_character_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course_character_relation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course_character_relation` (
  `course_character_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `character_id` INT NULL,
  PRIMARY KEY (`course_character_id`),
  UNIQUE INDEX `course_character_id_UNIQUE` (`course_character_id` ASC) VISIBLE,
  INDEX `course_course_char_relation_fk_idx` (`course_id` ASC) VISIBLE,
  INDEX `char_course_char_relation_fk_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `course_course_char_relation_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `char_course_char_relation_fk`
    FOREIGN KEY (`character_id`)
    REFERENCES `mydb`.`character` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`external_account_binding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`external_account_binding` ;

CREATE TABLE IF NOT EXISTS `mydb`.`external_account_binding` (
  `binding_id` INT NOT NULL,
  `binding_user_id` INT NOT NULL,
  `acc_identifier` VARCHAR(255) NULL,
  `acc_type` VARCHAR(45) NULL,
  PRIMARY KEY (`binding_id`, `binding_user_id`),
  UNIQUE INDEX `binding_id_UNIQUE` (`binding_id` ASC) VISIBLE,
  CONSTRAINT `user_acc_binding_fk`
    FOREIGN KEY (`binding_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`study_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`study_record` ;

CREATE TABLE IF NOT EXISTS `mydb`.`study_record` (
  `record_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `study_progress` INT NOT NULL,
  `study_score` INT NOT NULL,
  `study_time` DATETIME NOT NULL,
  PRIMARY KEY (`record_id`, `user_id`, `course_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) VISIBLE,
  INDEX `user_study_record_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `course_study_record_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `user_study_record_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_study_record_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL,
  `account` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `user_salt` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `account_UNIQUE` (`account` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_credential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_credential` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_credential` (
  `hash_id` INT NOT NULL,
  `hash_user_id` INT NOT NULL,
  `hash_user_pwd` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`hash_id`),
  UNIQUE INDEX `hash_id_UNIQUE` (`hash_id` ASC) VISIBLE,
  UNIQUE INDEX `hash_user_id_UNIQUE` (`hash_user_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
